include: linux: drv2624: Use unsigned for magic_number
Clang warns:
../kernel/motorola/msm8953/drivers/misc/drv2624.c:639:7: error: overflow converting case value to switch condition type (218879374337 to 4131009537) [-Werror,-Wswitch]
        case DRV2624_SET_SEQ_LOOP:
             ^
../kernel/motorola/msm8953/include/linux/drv2624.h:318:30: note: expanded from macro 'DRV2624_SET_SEQ_LOOP'
define DRV2624_SET_SEQ_LOOP    _IOWR(DRV2624_MAGIC_NUMBER, 1, \

Defines in C will default to int unless they inherit another time in their declaration (IE, long int, uint, char,uchar). As such, change DRV2626_MAGIC_NUMBER to uint so that every defines inherits this