drivers: misc: motomods: Use ushort instead of uchar
Clang warns:
../kernel/motorola/msm8953/drivers/misc/motomods/greybus/muc_svc.c:928:4: error: format specifies type 'unsigned short' but the argument has type '__u8' (aka 'unsigned char') [-Werror,-Wformat]
                        conn->intf1_id, conn->cport1_id,
                        ^~~~~~~~~~~~~~
../kernel/motorola/msm8953/include/linux/device.h:1154:58: note: expanded from macro 'dev_info'
                                                  ~~~    ^~~
../kernel/motorola/msm8953/drivers/misc/motomods/greybus/muc_svc.c:929:4: error: format specifies type 'unsigned short' but the argument has type '__u8' (aka 'unsigned char') [-Werror,-Wformat]
                        conn->intf2_id, conn->cport2_id);
                        ^~~~~~~~~~~~~~
../kernel/motorola/msm8953/include/linux/device.h:1154:58: note: expanded from macro 'dev_info'