sched/qhmp: Use bitwise AND instead of logical AND
../kernel/sched/qhmp_core.c:975:26: error: use of logical '&&' with constant operand [-Werror,-Wconstant-logical-operand]
        if ((irq_delta + steal) && sched_feat(NONTASK_CAPACITY))
                                ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../kernel/sched/qhmp_core.c:975:26: note: use '&' for a bitwise operation
        if ((irq_delta + steal) && sched_feat(NONTASK_CAPACITY))
                                ^~
                                &
../kernel/sched/qhmp_core.c:975:26: note: remove constant to silence this warning
        if ((irq_delta + steal) && sched_feat(NONTASK_CAPACITY))
                               ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Jarl-Penguin <jarlpenguin@outlook.com>